import numpy as np

def get_meta_dicom():
    allowed_meta_cols_fields = {
            'rowid': 'serial PRIMARY KEY',
            'DcmPathFlatten': 'varchar(255)',
            'phase': 'varchar(255)',
            'SeriesDate': 'varchar (255)',
            'StudyDate': 'varchar (255)',
            'TimeStamp': 'TIMESTAMP',
            'DateStamp': 'varchar(255)',
            'StudyTime': 'time',
            'SeriesTime': 'time',
            'BodyPartExamined': 'varchar(255)',
            'Modality': 'varchar(255)',
            'PatientID': 'varchar(255)',
            'PatientSex': 'varchar(255)',
            'StudyInstanceUID': 'varchar(255)',
            'SeriesInstanceUID': 'varchar(255)',
            'SOPInstanceUID': 'varchar(255)',
            'SOPClassUID': 'varchar(255)',
            'StudyDescription': 'varchar(255)',
            'SeriesDescription': 'varchar(255)',
            'AcquisitionDate': 'varchar(255)',
            'ProtocolName': 'varchar(255)',
            'PatientAddress': 'varchar(255)',
            'AccessionNumber': 'varchar(255)',
            'AdditionalPatientHistory': 'varchar(255)',
            'Manufacturer': 'varchar(255)',
            'InstitutionalName': 'varchar(255)',
            'NumberOfFrames': 'int8',
            'FrameIncrementPointer': 'varchar(255)',
            'FrameTime': 'float8',
            'PositionerMotion': 'varchar(255)',
            'DistanceSourceToPatient': 'float8',
            'DistanceSourceToDetector': 'float8',
            'PositionerPrimaryAngle': 'float8',
            'PositionerSecondaryAngle': 'float8',
            'CineRate': 'float8',
            'labels': 'int8',
            'labels_transformed': 'int8',
            'predictions': 'int8',
            'confidences': 'TEXT []',
            'labels_predictions': 'int8',
            'labels_confidences': 'varchar(255)',
            'labels_transformed_predictions': 'int8',
            'duration_transformed': 'int8',
            'labels_transformed_confidences': 'varchar(255)',
            'diagnostic_data': 'BOOLEAN',
            "sten_proc_1_prox_rca_transformed": 'float8',
            "sten_proc_2_midt_rca_transformed": 'float8',
            "sten_proc_3_dist_rca_transformed": 'float8',
            "sten_proc_4_pda_transformed": 'float8',
            "sten_proc_5_lm_transformed": 'float8',
            "sten_proc_6_prox_lad_transformed": 'float8',
            "sten_proc_7_midt_lad_transformed": 'float8',
            "sten_proc_8_dist_lad_transformed": 'float8',
            "sten_proc_9_d1_transformed": 'float8',
            "sten_proc_10_d2_transformed": 'float8',
            "sten_proc_11_prox_lcx_transformed": 'float8',
            "sten_proc_12_om1_transformed": 'float8',
            "sten_proc_13_midt_lcx_transformed": 'float8',
            "sten_proc_14_om2_transformed": 'float8',
            "sten_proc_15_dist_lcx_transformed": 'float8',
            "sten_proc_16_pla_rca_transformed": 'float8',
            "sten_proc_1_prox_rca_transformed_predictions": 'float8',
            "sten_proc_2_midt_rca_transformed_predictions": 'float8',
            "sten_proc_3_dist_rca_transformed_predictions": 'float8',
            "sten_proc_4_pda_transformed_predictions": 'float8',
            "sten_proc_5_lm_transformed_predictions": 'float8',
            "sten_proc_6_prox_lad_transformed_predictions": 'float8',
            "sten_proc_7_midt_lad_transformed_predictions": 'float8',
            "sten_proc_8_dist_lad_transformed_predictions": 'float8',
            "sten_proc_9_d1_transformed_predictions": 'float8',
            "sten_proc_10_d2_transformed_predictions": 'float8',
            "sten_proc_11_prox_lcx_transformed_predictions": 'float8',
            "sten_proc_12_om1_transformed_predictions": 'float8',
            "sten_proc_13_midt_lcx_transformed_predictions": 'float8',
            "sten_proc_14_om2_transformed_predictions": 'float8',
            "sten_proc_15_dist_lcx_transformed_predictions": 'float8',
            "sten_proc_16_pla_rca_transformed_predictions": 'float8',    
            "sten_proc_1_prox_rca_transformed_confidences": 'varchar(255)',
            "sten_proc_2_midt_rca_transformed_confidences": 'varchar(255)',
            "sten_proc_3_dist_rca_transformed_confidences": 'varchar(255)',
            "sten_proc_4_pda_transformed_confidences": 'varchar(255)',
            "sten_proc_5_lm_transformed_confidences": 'varchar(255)',
            "sten_proc_6_prox_lad_transformed_confidences": 'varchar(255)',
            "sten_proc_7_midt_lad_transformed_confidences": 'varchar(255)',
            "sten_proc_8_dist_lad_transformed_confidences": 'varchar(255)',
            "sten_proc_9_d1_transformed_confidences": 'varchar(255)',
            "sten_proc_10_d2_transformed_confidences": 'varchar(255)',
            "sten_proc_11_prox_lcx_transformed_confidences": 'varchar(255)',
            "sten_proc_12_om1_transformed_confidences": 'varchar(255)',
            "sten_proc_13_midt_lcx_transformed_confidences": 'varchar(255)',
            "sten_proc_14_om2_transformed_confidences": 'varchar(255)',
            "sten_proc_15_dist_lcx_transformed_confidences": 'varchar(255)',
            "sten_proc_16_pla_rca_transformed_confidences": 'varchar(255)',
            "ffr_proc_1_prox_rca_transformed": 'float8',
            "ffr_proc_2_midt_rca_transformed": 'float8',
            "ffr_proc_3_dist_rca_transformed": 'float8',
            "ffr_proc_4_pda_transformed": 'float8',
            "ffr_proc_5_lm_transformed": 'float8',
            "ffr_proc_6_prox_lad_transformed": 'float8',
            "ffr_proc_7_midt_lad_transformed": 'float8',
            "ffr_proc_8_dist_lad_transformed": 'float8',
            "ffr_proc_9_d1_transformed": 'float8',
            "ffr_proc_10_d2_transformed": 'float8',
            "ffr_proc_11_prox_lcx_transformed": 'float8',
            "ffr_proc_12_om1_transformed": 'float8',
            "ffr_proc_13_midt_lcx_transformed": 'float8',
            "ffr_proc_14_om2_transformed": 'float8',
            "ffr_proc_15_dist_lcx_transformed": 'float8',
            "ffr_proc_16_pla_rca_transformed": 'float8',
            "ffr_proc_1_prox_rca_transformed_predictions": 'float8',
            "ffr_proc_2_midt_rca_transformed_predictions": 'float8',
            "ffr_proc_3_dist_rca_transformed_predictions": 'float8',
            "ffr_proc_4_pda_transformed_predictions": 'float8',
            "ffr_proc_5_lm_transformed_predictions": 'float8',
            "ffr_proc_6_prox_lad_transformed_predictions": 'float8',
            "ffr_proc_7_midt_lad_transformed_predictions": 'float8',
            "ffr_proc_8_dist_lad_transformed_predictions": 'float8',
            "ffr_proc_9_d1_transformed_predictions": 'float8',
            "ffr_proc_10_d2_transformed_predictions": 'float8',
            "ffr_proc_11_prox_lcx_transformed_predictions": 'float8',
            "ffr_proc_12_om1_transformed_predictions": 'float8',
            "ffr_proc_13_midt_lcx_transformed_predictions": 'float8',
            "ffr_proc_14_om2_transformed_predictions": 'float8',
            "ffr_proc_15_dist_lcx_transformed_predictions": 'float8',
            "ffr_proc_16_pla_rca_transformed_predictions": 'float8',    
            "ffr_proc_1_prox_rca_transformed_confidences": 'varchar(255)',
            "ffr_proc_2_midt_rca_transformed_confidences": 'varchar(255)',
            "ffr_proc_3_dist_rca_transformed_confidences": 'varchar(255)',
            "ffr_proc_4_pda_transformed_confidences": 'varchar(255)',
            "ffr_proc_5_lm_transformed_confidences": 'varchar(255)',
            "ffr_proc_6_prox_lad_transformed_confidences": 'varchar(255)',
            "ffr_proc_7_midt_lad_transformed_confidences": 'varchar(255)',
            "ffr_proc_8_dist_lad_transformed_confidences": 'varchar(255)',
            "ffr_proc_9_d1_transformed_confidences": 'varchar(255)',
            "ffr_proc_10_d2_transformed_confidences": 'varchar(255)',
            "ffr_proc_11_prox_lcx_transformed_confidences": 'varchar(255)',
            "ffr_proc_12_om1_transformed_confidences": 'varchar(255)',
            "ffr_proc_13_midt_lcx_transformed_confidences": 'varchar(255)',
            "ffr_proc_14_om2_transformed_confidences": 'varchar(255)',
            "ffr_proc_15_dist_lcx_transformed_confidences": 'varchar(255)',
            "ffr_proc_16_pla_rca_transformed_confidences": 'varchar(255)',
            "kommentar": 'varchar(255)',
            "text_raw": 'varcahr(225'
                  
            
            
            
            }
    return allowed_meta_cols_fields




def get_meta_arcade():
    keys =['labels_predictions', 'treatment_transformed', 'koronarpatologi_transformed', 'duration_transformed', 'event', 'kommentar', "text_raw",
     'labels_transformed', 'labels_transformed_predictions', 'labels_transformed_confidences', "id", "image_id",
     'sten_proc_1_prox_rca_transformed', 'sten_proc_2_midt_rca_transformed', 'sten_proc_3_dist_rca_transformed', 'sten_proc_4_pda_transformed','sten_proc_5_lm_transformed', 'sten_proc_16_pla_rca_transformed', 'sten_proc_6_prox_lad_transformed', 'sten_proc_7_midt_lad_transformed', 'sten_proc_8_dist_lad_transformed', 'sten_proc_9_d1_transformed', 'sten_proc_10_d2_transformed', 'sten_proc_11_prox_lcx_transformed', 'sten_proc_12_om1_transformed', 'sten_proc_13_midt_lcx_transformed', 'sten_proc_14_om2_transformed', 'sten_proc_15_dist_lcx_transformed',
     'sten_proc_1_prox_rca_transformed_confidences', 'sten_proc_2_midt_rca_transformed_confidences', 'sten_proc_3_dist_rca_transformed_confidences', 'sten_proc_4_pda_transformed_confidences', 'sten_proc_5_lm_transformed_confidences', 'sten_proc_16_pla_rca_transformed_confidences', 'sten_proc_6_prox_lad_transformed_confidences', 'sten_proc_7_midt_lad_transformed_confidences', 'sten_proc_8_dist_lad_transformed_confidences', 'sten_proc_9_d1_transformed_confidences', 'sten_proc_10_d2_transformed_confidences', 'sten_proc_11_prox_lcx_transformed_confidences', 'sten_proc_12_om1_transformed_confidences', 'sten_proc_13_midt_lcx_transformed_confidences', 'sten_proc_14_om2_transformed_confidences', 'sten_proc_15_dist_lcx_transformed_confidences',
     'sten_proc_1_prox_rca_transformed_predictions', 'sten_proc_2_midt_rca_transformed_predictions', 'sten_proc_3_dist_rca_transformed_predictions', 'sten_proc_4_pda_transformed_predictions', 'sten_proc_5_lm_transformed_predictions', 'sten_proc_16_pla_rca_transformed_predictions', 'sten_proc_6_prox_lad_transformed_predictions', 'sten_proc_7_midt_lad_transformed_predictions', 'sten_proc_8_dist_lad_transformed_predictions', 'sten_proc_9_d1_transformed_predictions', 'sten_proc_10_d2_transformed_predictions', 'sten_proc_11_prox_lcx_transformed_predictions', 'sten_proc_12_om1_transformed_predictions', 'sten_proc_13_midt_lcx_transformed_predictions', 'sten_proc_14_om2_transformed_predictions', 'sten_proc_15_dist_lcx_transformed_predictions',
     'ffr_proc_1_prox_rca_transformed', 'ffr_proc_2_midt_rca_transformed', 'ffr_proc_3_dist_rca_transformed', 'ffr_proc_4_pda_transformed','ffr_proc_5_lm_transformed', 'ffr_proc_16_pla_rca_transformed', 'ffr_proc_6_prox_lad_transformed', 'ffr_proc_7_midt_lad_transformed', 'ffr_proc_8_dist_lad_transformed', 'ffr_proc_9_d1_transformed', 'ffr_proc_10_d2_transformed', 'ffr_proc_11_prox_lcx_transformed', 'ffr_proc_12_om1_transformed', 'ffr_proc_13_midt_lcx_transformed', 'ffr_proc_14_om2_transformed', 'ffr_proc_15_dist_lcx_transformed',
     'ffr_proc_1_prox_rca_transformed_confidences', 'ffr_proc_2_midt_rca_transformed_confidences', 'ffr_proc_3_dist_rca_transformed_confidences', 'ffr_proc_4_pda_transformed_confidences', 'ffr_proc_5_lm_transformed_confidences', 'ffr_proc_16_pla_rca_transformed_confidences', 'ffr_proc_6_prox_lad_transformed_confidences', 'ffr_proc_7_midt_lad_transformed_confidences', 'ffr_proc_8_dist_lad_transformed_confidences', 'ffr_proc_9_d1_transformed_confidences', 'ffr_proc_10_d2_transformed_confidences', 'ffr_proc_11_prox_lcx_transformed_confidences', 'ffr_proc_12_om1_transformed_confidences', 'ffr_proc_13_midt_lcx_transformed_confidences', 'ffr_proc_14_om2_transformed_confidences', 'ffr_proc_15_dist_lcx_transformed_confidences',
     'ffr_proc_1_prox_rca_transformed_predictions', 'ffr_proc_2_midt_rca_transformed_predictions', 'ffr_proc_3_dist_rca_transformed_predictions', 'ffr_proc_4_pda_transformed_predictions', 'ffr_proc_5_lm_transformed_predictions', 'ffr_proc_16_pla_rca_transformed_predictions', 'ffr_proc_6_prox_lad_transformed_predictions', 'ffr_proc_7_midt_lad_transformed_predictions', 'ffr_proc_8_dist_lad_transformed_predictions', 'sten_proc_9_d1_transformed_predictions', 'sten_proc_10_d2_transformed_predictions', 'sten_proc_11_prox_lcx_transformed_predictions', 'sten_proc_12_om1_transformed_predictions', 'sten_proc_13_midt_lcx_transformed_predictions', 'sten_proc_14_om2_transformed_predictions', 'sten_proc_15_dist_lcx_transformed_predictions'

    ]
    values = ['int8', 'int8', 'int8', 'int8', 'int8', 'TEXT []', 'TEXT []',
        'int8', 'int8', 'varchar(255)', 'int8', 'int8',
        'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8',
        'varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)',
        'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8',
        'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8',
        'varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)','varchar(255)',
        'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8','int8', 'int8', 'int8', 'int8']

    allowed_meta_cols_fields = dict(zip(keys, values))
    # update with the dicom fields
    allowed_meta_cols_fields.update(get_meta_dicom())
    return allowed_meta_cols_fields
# def get_meta_dicom_pd():
#     pandas_fields = {
#             'rowid': np.in32,
#             'DcmPathFlatten': str,
#             'SeriesDate': 'varchar (255)',
#             'TimeStamp': 'TIMESTAMP',
#             'DateStamp': str,
#             'StudyTime': 'time',
#             'SeriesTime': 'time',
#             'BodyPartExamined': str,
#             'Modality': str,
#             'PatientID': str,
#             'StudyInstanceUID': str,
#             'SeriesInstanceUID': str,
#             'SOPInstanceUID': str,
#             'StudyDescription': str,
#             'SeriesDescription': str,
#             'AdditionalPatientHistory': str,
#             'Manufacturer': str,
#             'InstitutionalName': str,
#             'NumberOfFrames': 'int8',
#             'FrameIncrementPointer': str,
#             'FrameTime': 'float8',
#             'PositionerMotion': str,
#             'DistanceSourceToPatient': 'float8',
#             'DistanceSourceToDetector': 'float8',
#             'PositionerPrimaryAngle': 'float8',
#             'PositionerSecondaryAngle': 'float8',
#             'CineRate': 'float8',
#             'labels': 'int8',
#             'labels_transformed': 'int8',
#             'predictions': 'int8',
#             'confidences': 'TEXT []'
#             }
#     return pandas_fields
