
def get_meta_pats():
    allowed_meta_cols_fields = {
        "rowid": 'BIGINT PRIMARY KEY',
        "bth_pid": 'varchar(255)',
        "entryid": 'int8',
        "previousentry": 'float8',
        "nextentry": 'float8',
        "henvistfrahospital": 'float8',
        "henvistfra_andet": 'varchar(255)',
        "henvisningsdato": 'float8',
        "indl_ggelsesdato": 'float8',
        "proceduredato": 'varchar(255)',
        "ventetid_beregnes": 'varchar(255)',
        "prioritet": 'varchar(255)',
        "hospital_indlagt": 'float8',
        "afdeling": 'varchar(255)',
        "henvisningsdiagnose": 'varchar(255)',
        "henvisningsdiagnose_anden": 'TEXT',
        "pakkeforl_b": 'varchar(255)',
        "hypertension": 'varchar(255)',
        "hyperlipid_mi": 'varchar(255)',
        "diabetes": 'varchar(255)',
        "diabetestype": 'varchar(255)',
        "familiary_ihd": 'varchar(255)',
        "rygning": 'varchar(255)',
        "antalpakke_r": 'varchar(255)',
        "tidligereapopleksi_rind_tci": 'varchar(255)',
        "type_tidl_apopleksi_rind_tci": 'varchar(255)',
        "extracardiacarteriopathy": 'varchar(255)',
        "type_periferarteriesygdom": 'varchar(255)',
        "stabilangina_ccsklasse": 'varchar(255)',
        "tidligereami_frasetevt_aktuellestemiel_nstemi": 'varchar(255)',
        "antaltidligereami": 'float8',
        "senestami": 'varchar(255)',
        "kendthjerteklapsygdom": 'varchar(255)',
        "hjerteklapsygdom_type": 'varchar(255)',
        "tidligerehjerteklapoperation": 'varchar(255)',
        "hjerteklapoperation_type": 'varchar(255)',
        "anamnestiskhjertesvigt": 'varchar(255)',
        "nyhaklasse": 'varchar(255)',
        "arytmi": 'varchar(255)',
        "arytmi_type": 'varchar(255)',
        "arytmidevice": 'varchar(255)',
        "kendtkongenithj_sygdom": 'varchar(255)',
        "aktivendokardit_antibiot_beh_": 'varchar(255)',
        "ekkoudf_rt": 'varchar(255)',
        "ekkodato": 'varchar(255)',
        "ejectionfractionvalueifknown": 'varchar(255)',
        "ejectionfractioncategory": 'varchar(255)',
        "betydendevalvulopati": 'varchar(255)',
        "pasystolicifknown": 'float8',
        "isk_mitest_3mdr": 'varchar(255)',
        "tidligerepci": 'varchar(255)',
        "antaltidligerepci": 'float8',
        "senestepci": "varchar(255)",
        "tidligerecabg": 'varchar(255)',
        "antaltidligerecabg": "varchar(255)",
        "senestecabg": "varchar(255)",
        "hjertetransplantation": 'varchar(255)',
        "numberofpreviousheartoperations": "float8",
        "historyofpulmonarydisease": 'varchar(255)',
        "fev1": "float8",
        "fev1__afforventet": 'float8',
        "se_creatinin": "float8",
        "renaldiseaseatthetimeofsurgery": 'varchar(255)',
        "_getbl_dningsrisiko": 'varchar(255)',
        "kommentar_bl_dningsrisiko": 'TEXT',
        "anamnese_kort": 'TEXT',
        "weight_kg": "float8",
        "height_cm": 'float8',
        "bmi": "float8",
        "bsa": "float8",
        "puls": "float8",
        "sbt": "float8",
        "dbt": "float8",
        "pulsa_fem_dxt": 'varchar(255)',
        "pulsa_fem_sin": 'varchar(255)',
        "allen_stestdxt": 'varchar(255)',
        "allen_stestsin": 'varchar(255)',
        "udtaltevaricerel_tidl_veneh_st": 'varchar(255)',
        "abnormtekg": 'varchar(255)',
        "arytmi1": 'varchar(255)',
        "arytmitype1": 'varchar(255)',
        "abnormqrskonfig__st_t": 'varchar(255)',
        "abnormqrskonfig__st_t_type": 'varchar(255)',
        "lokalisationvedstemi": 'varchar(255)',
        "troponint_iel_mark_rer": 'varchar(255)',
        "operativeurgency": 'varchar(255)',
        "cardiacprocedures": 'varchar(255)',
        "othercardiacprocedures": 'varchar(255)',
        "otherthoracicandvascularprocedures": 'float8',
        "nativevalvepathology": 'float8',
        "intervalbetweensurgeryandlastmi": 'varchar(255)',
        "neurologicaldysfunction": 'varchar(255)',
        "killipklassevedami": 'varchar(255)',
        "kardiogentshockf_rprocedure": 'varchar(255)',
        "kritiskpr_operativtilstand": 'varchar(255)',
        "intravenousnitratesoranyheparin": 'varchar(255)',
        "pre_operativeheartrhythm": 'varchar(255)',
        "intravenousinotropespriortoanaesthesia": 'varchar(255)',
        "impella": 'varchar(255)',
        "ventilatedpreoperation": 'varchar(255)',
        "genopliverefterinstitio": 'varchar(255)',
        "indikationforkag": 'varchar(255)',
        "indikationforkag_anden": 'varchar(255)',
        "aktuelindikation": 'varchar(255)',
        "cdnummer__registryentrynumber": 'varchar(255)',
        "inkluderetividenskabeligunders_gelse": 'float8',
        "ankomstkard_lab": 'varchar(255)',
        "timestamp": "TIMESTAMP",
        "kateterud": 'varchar(255)',
        "procedurensvarighed_beregnes": 'float8',
        "karadgang": 'varchar(255)',
        "kateterst_rrelse_charriere_f": 'float8',
        "gennemlysningstid_sek": 'float8',
        "gennemlysningstid_min": 'float8',
        "r_ntgenstr_ledosis": 'float8',
        "kontrastvolumen": 'float8',
        "kontrastmiddelnavn": 'varchar(255)',
        "lukkedevice": 'varchar(255)',
        "dominans": 'varchar(255)',
        "venegrafter_antalcentraleanastomoser": 'float8',
        "graftstatus_beskriv": 'TEXT',
        "antalsignifikantestenoser": 'float8',
        "koronarpatologi_nativekar_udfyldesforallept_": 'varchar(255)',
        "koronarpatologi_tidligerecabg": 'varchar(255)',
        "lmstenose": 'varchar(255)',
        "stentthrombose": 'varchar(255)',
        "us_dvanligeangiografiskefund": 'TEXT',
        "us_dvanligeangiografiskefund_beskriv": 'TEXT',
        "intraaorticballoonpumpused": 'varchar(255)',
        "additiveeuroscore": 'float8',
        "logisticeuroscore": 'float8',
        "konsekvens": "varchar(255)",
        "kommentar": 'TEXT',
        "ordinationer": 'TEXT',
        "procedurekodervenstrekat": 'varchar(255)',
        "procedureskskode_forunders_gelse": 'varchar(255)',
        "aktionsdiagnose_a": 'varchar(255)',
        "bidiagnoser_b": 'varchar(255)',
        "bidiagnoser_b__andre": 'varchar(255)',
        "diagnoseefterkag": 'varchar(255)',
        "periproceduralekomplikationer": 'varchar(255)',
        "periproceduralekomplikationer_type": 'varchar(255)',
        "datoforthoraxkonf": 'float8',
        "konklusion_thoraxkonf": 'varchar(255)',
        "referat_thoraxkonf": 'TEXT',
        "indstiksrelateredekomplikationer": 'varchar(255)',
        "h_ndelserunderindl_ggelse": 'varchar(255)',
        "udskrivningsdato": 'float8',
        "udskrivning": 'varchar(255)',
        "kommentartilindl_ggelse_behandlingsplan": 'TEXT',
        "indkaldestilkliniskkontrolvialokalsygehus": 'varchar(255)',
        "diabetes1": 'varchar(255)',
        "diabetesdebut_r": 'float8',
        "cerebrovascul_rlidelse": 'varchar(255)',
        "periferkarsygdom": 'varchar(255)',
        "lungefunktion": 'varchar(255)',
        "pulmonalhypertensiongl": 'varchar(255)',
        "mave_tarmlidelse": 'varchar(255)',
        "andrerisikofaktorer": 'varchar(255)',
        "ustabilangina_klasse_1_2eller3": 'varchar(255)',
        "kliniskeomst_ndigheder_klasse_a_bellerc": 'varchar(255)',
        "beh_intensitet_1_2eller3": 'varchar(255)',
        "tidl_hjertekirurgiogptca": 'varchar(255)',
        "senestem_ned__r": 'varchar(255)',
        "senestem_ned__rptca": 'varchar(255)',
        "amitidspunkter_aktuelogtidl_": 'varchar(255)',
        "timerfrasymtomdebuttilankomst": 'float8',
        "type": 'varchar(255)',
        "andenhjertesygdom": 'varchar(255)',
        "samletstelevationimm": 'float8',
        "invasiveunders_gelser": 'varchar(255)',
        "indikationforunders_gelse": 'varchar(255)',
        "venegraftperiferanastomoser": 'varchar(255)',
        "limaanastomosetilsegment": 'varchar(255)',
        "rimaanastomosetilsegment1": 'varchar(255)',
        "radialisgrafttilsegment": 'varchar(255)',
        "aepiploicatilsegment": 'varchar(255)',
        "koronarpatologi1": 'varchar(255)',
        "konklusion_kard_lab_konf": 'varchar(255)',
        "kirurgiskplanl_gning": 'varchar(255)',
        "ptca_prioritet": 'varchar(255)',
        "version": 'varchar(255)',
        "Sten %: 1 Prox RCA": 'float8',
        "Sten %: 10 D2": 'float8',
        "Sten %: 11 Prox LCX": 'float8',
        "Sten %: 12 OM1": 'float8',
        "Sten %: 13 Midt LCX": 'float8',
        "Sten %: 14 OM2": 'float8',
        "Sten %: 15 Distale LCX": 'float8',
        "Sten %: 16 PLA fra RCA": 'float8',
        "Sten %: 2 Midt RCA": 'float8',
        "Sten %: 3 Distale RCA": 'float8',
        "Sten %: 4 PDA": 'float8',
        "Sten %: 5 LM": 'float8',
        "Sten %: 6 Prox LAD": 'float8',
        "Sten %: 7 Midt LAD": 'float8',
        "Sten %: 8 Distale LAD": 'float8',
        "Sten %: 9 D1": 'float8',
        "ffr %: 1 Prox RCA": 'float8',
        "ffr %: 10 D2": 'float8',
        "ffr %: 11 Prox LCX": 'float8',
        "ffr %: 12 OM1": 'float8',
        "ffr %: 13 Midt LCX": 'float8',
        "ffr %: 14 OM2": 'float8',
        "ffr %: 15 Distale LCX": 'float8',
        "ffr %: 16 PLA fra RCA": 'float8',
        "ffr %: 2 Midt RCA": 'float8',
        "ffr %: 3 Distale RCA": 'float8',
        "ffr %: 4 PDA": 'float8',
        "ffr %: 5 LM": 'float8',
        "ffr %: 6 Prox LAD": 'float8',
        "ffr %: 7 Midt LAD": 'float8',
        "ffr %: 8 Distale LAD": 'float8',
        "ffr %: 9 D1": 'float8',
        "kartype: 1 Prox RCA": 'varchar(255)',
        "kartype: 10 D2": 'varchar(255)',
        "kartype: 11 Prox LCX": 'varchar(255)',
        "kartype: 12 OM1": 'varchar(255)',
        "kartype: 13 Midt LCX": 'varchar(255)',
        "kartype: 14 OM2": 'varchar(255)',
        "kartype: 15 Distale LCX": 'varchar(255)',
        "kartype: 16 PLA fra RCA": 'varchar(255)',
        "kartype: 2 Midt RCA": 'varchar(255)',
        "kartype: 3 Distale RCA": 'varchar(255)',
        "kartype: 4 PDA": 'varchar(255)',
        "kartype: 5 LM": 'varchar(255)',
        "kartype: 6 Prox LAD": 'varchar(255)',
        "kartype: 7 Midt LAD": 'varchar(255)',
        "kartype: 8 Distale LAD": 'varchar(255)',
        "kartype: 9 D1": 'varchar(255)'}
    return allowed_meta_cols_fields
